from weather.wwo.italy import location_for_postcode


def test_location_for_postcode():
	assert location_for_postcode('00118') == 'Roma, Lazio'
	assert location_for_postcode('01100') == 'Viterbo, Lazio'
	assert location_for_postcode('02100') == 'Rieti, Lazio'
	assert location_for_postcode('03100') == 'Frosinone, Lazio'
	assert location_for_postcode('04100') == 'Latina, Lazio'
	assert location_for_postcode('05100') == 'Terni, Umbria'
	assert location_for_postcode('06121') == 'Perugia, Umbria'
	assert location_for_postcode('07100') == 'Sassari, Sardegna'
	assert location_for_postcode('07026') == 'Olbia, Sardegna'
	assert location_for_postcode('07029') == 'Tempio Pausania, Sardegna'
	assert location_for_postcode('08100') == 'Nuoro, Sardegna'
	assert location_for_postcode('08045') == 'Lanusei, Sardegna'
	assert location_for_postcode('08048') == 'Tortoli, Sardegna'
	assert location_for_postcode('09121') == 'Cagliari, Sardegna'
	assert location_for_postcode('09170') == 'Oristano, Sardegna'
	assert location_for_postcode('09013') == 'Carbonia, Sardegna'
	assert location_for_postcode('09016') == 'Iglesias, Sardegna'
	assert location_for_postcode('09025') == 'Sanluri, Sardegna'
	assert location_for_postcode('09039') == 'Villacidro, Sardegna'
	assert location_for_postcode('10121') == 'Torino, Piemonte'
	assert location_for_postcode('11100') == 'Aosta, Valle d\'Aosta'
	assert location_for_postcode('12100') == 'Cuneo, Piemonte'
	assert location_for_postcode('13100') == 'Vercelli, Piemonte'
	assert location_for_postcode('13900') == 'Biella, Piemonte'
	assert location_for_postcode('14100') == 'Asti, Piemonte'
	assert location_for_postcode('15100') == 'Alessandria, Piemonte'
	assert location_for_postcode('16121') == 'Genova, Liguria'
	assert location_for_postcode('17100') == 'Savona, Liguria'
	assert location_for_postcode('18100') == 'Imperia, Liguria'
	assert location_for_postcode('19121') == 'La Spezia, Liguria'
	assert location_for_postcode('20121') == 'Milan, Lombardia'
	assert location_for_postcode('20900') == 'Monza, Lombardia'
	assert location_for_postcode('21100') == 'Varese, Lombardia'
	assert location_for_postcode('22100') == 'Como, Lombardia'
	assert location_for_postcode('23100') == 'Sondrio, Lombardia'
	assert location_for_postcode('23900') == 'Lecco, Lombardia'
	assert location_for_postcode('24121') == 'Bergamo, Lombardia'
	assert location_for_postcode('25121') == 'Brescia, Lombardia'
	assert location_for_postcode('26100') == 'Cremona, Lombardia'
	assert location_for_postcode('26900') == 'Lodi, Lombardia'
	assert location_for_postcode('27100') == 'Pavia, Lombardia'
	assert location_for_postcode('28100') == 'Novara, Piemonte'
	assert location_for_postcode('28921') == 'Verbania, Piemonte'
	assert location_for_postcode('29100') == 'Piacenza, Emilia-Romagna'
	assert location_for_postcode('30121') == 'Venezia, Veneto'
	assert location_for_postcode('31100') == 'Treviso, Veneto'
	assert location_for_postcode('32100') == 'Belluno, Veneto'
	assert location_for_postcode('33100') == 'Udine, Friuli-Venezia Giulia'
	assert location_for_postcode('33170') == 'Pordenone, Friuli-Venezia Giulia'
	assert location_for_postcode('34121') == 'Trieste, Friuli-Venezia Giulia'
	assert location_for_postcode('34170') == 'Gorizia, Friuli-Venezia Giulia'
	assert location_for_postcode('35121') == 'Padova, Veneto'
	assert location_for_postcode('36100') == 'Vicenza, Veneto'
	assert location_for_postcode('37121') == 'Verona, Veneto'
	assert location_for_postcode('38121') == 'Trento, Trentino-Alto Adige'
	assert location_for_postcode('39100') == 'Bolzano, Trentino-Alto Adige'
	assert location_for_postcode('40121') == 'Bologna, Emilia-Romagna'
	assert location_for_postcode('41121') == 'Modena, Emilia-Romagna'
	assert location_for_postcode('42121') == 'Reggio nell\'Emilia, Emilia-Romagna'
	assert location_for_postcode('43100') == 'Parma, Emilia-Romagna'
	assert location_for_postcode('44100') == 'Ferrara, Emilia-Romagna'
	assert location_for_postcode('45100') == 'Rovigo, Veneto'
	assert location_for_postcode('46100') == 'Mantova, Lombardia'
	assert location_for_postcode('47121') == 'Forli, Emilia-Romagna'
	assert location_for_postcode('47521') == 'Cesena, Emilia-Romagna'
	assert location_for_postcode('47921') == 'Rimini, Emilia-Romagna'


